### ISSUE TITLE
Use inkscape's updated code?

### ISSUE THREAD

**Issue by berleant** [evil-mad/ink_extensions#2]
It looks to me like inkscape has significantly updated their extension code here: https://gitlab.com/inkscape/extensions (e.g. the `inkex` folder). Should we update this repo as well? Unfortunately that probably means some work in AxiCli/AxiDraw-Internal/etc will be needed to keep everything running correctly.

**Comment by oskay** [comment]
No; that is far enough pre-release that it shouldn't be considered stable yet. I'm releasing and contributing one new piece of software, Hershey Text, which is built against that, so that it can hopefully be included in the future release of Inkscape 1.0.

For the rest of our software, we will update the interface when new version of Inkscape is closer to release. It's good to be aware of this set of changes -- we'll get to use argparse, amongst other great changes -- but it's still not near term yet.
